#!/usr/bin/env ruby

require 'dwarftree'
require 'optparse'

dies = nil
subroutines = nil

objects = OptionParser.new do |o|
  o.banner = "Usage: #{$0} OBJECT"
  o.on('-d', '--die TAG1,TAG2,...', String, 'Show only specified DIEs') do |d|
    dies ||= []
    dies += d.split(',')
  end
  o.on('-s', '--subroutine NAME1,NAME2,...', String, 'Show only specified subroutines') do |s|
    subroutines ||= []
    subroutines += s.split(',')
  end
end.parse!(ARGV)

objects.each do |object|
  Dwarftree.run(object, dies: dies, subroutines: subroutines)
end
