#!/usr/bin/env ruby

require 'dwarftree'
require 'optparse'
require 'set'

subprograms = Set.new
dies = Set.new
show_size = false
sort_size = false
flat = false

objects = OptionParser.new do |o|
  o.banner = "Usage: #{$0} OBJECT"
  o.on('-S', '--subprogram NAME1,NAME2,...', String, 'Show only specified subprograms and their children') do |ss|
    ss.split(',').each { |s| subprograms.add(s) }
  end
  o.on('--die TAG1,TAG2,...', String, 'Show only specified DIEs') do |ds|
    ds.split(',').each { |d| dies.add(d) }
  end
  o.on('--show-size', 'Show code size for DIEs which have the information') do
    show_size = true
  end
  o.on('--sort-size', 'Show code size and sort sibling DIEs by it') do
    show_size = true
    sort_size = true
  end
  o.on('--flat', 'Skip constructing a tree') do
    flat = true
  end
end.parse!(ARGV)

objects.each do |object|
  Dwarftree.run(object, dies: dies, subprograms: subprograms, show_size: show_size, sort_size: sort_size, flat: flat)
end
